// WARNING: this file was auto-generated by Grime

// +build !js

package grime

import "github.com/katsuya94/grime/runtime"

var Library *runtime.Library

func init() {
	Library = runtime.MustNewLibraryFromFile("grime")
}
