(library (grime)
  (export
    quote
    syntax
    if
    let*
    begin
    lambda
    define
    define-syntax
    syntax-case
    set!
    _
    ...
    cons
    not
    car
    cdr
    null?
    pair?
    write
    call/cc
    error
    eqv?
    syntax->datum
    identifier?
    eq?
    equal?
    when
    unless
    let
    and
    or
    list?
    fold-left
    for-all
    syntax-rules)
  (import
    (for (except (base) syntax syntax-case set! _ ... syntax-rules) run expand)
    (for (only (base) syntax syntax-case syntax-case set! _ ... syntax-rules) run expand)))